# Generated by Django 3.1.2 on 2020-12-18 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fb', '0006_post_is_liked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frends', models.ManyToManyField(related_name='my_friends', to=settings.AUTH_USER_MODEL)),
                ('i_requested', models.ManyToManyField(related_name='i_requested', to=settings.AUTH_USER_MODEL)),
                ('requested_me', models.ManyToManyField(related_name='requested_me', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
