# Generated by Django 3.1.2 on 2020-12-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0007_relation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Relation',
        ),
    ]
