# Generated by Django 3.1.2 on 2020-12-19 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0009_relation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='frends',
            new_name='friends',
        ),
    ]
