# Generated by Django 3.1.2 on 2021-01-28 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0011_group_groupspost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
