# Generated by Django 3.1.2 on 2021-02-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0013_testgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='joined',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='TestGroup',
        ),
    ]
