# Generated by Django 3.1.2 on 2021-03-10 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0019_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('-date',)},
        ),
    ]
