# Generated by Django 3.1.2 on 2021-03-22 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0020_auto_20210310_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('date',)},
        ),
    ]
